- name: Add a new user named testuser
  user:
    name: testuser
    password: "{{ testuser_password }}"

- name: Add testuser user to the sudoers
  copy:
    dest: "/etc/sudoers.d/testuser"
    content: "testuser  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key:
    user: testuser
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes

- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  notify:
    - restart ssh

