- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - debug:
        msg: "Executing tasks from add_user role"
    - include_role:
        name: userfile
        tasks_from: add_user.yml

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy HTML file
      copy:
        src: index.html
        dest: /var/www/html
      notify:
        - Reload Nginx

    - name: Deploy CSS file
      copy:
        src: styles.css
        dest: /var/www/html
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

